### ISSUE TITLE
Retrieve variants in the callset

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1243]
Hi,

I am unable to retrieve the variants in our cohort for RAI1 using the 'seqr' link. Variant link - https://seqr.broadinstitute.org/project/R0358_cmg_vcgs_exomes/saved_variants/variant/SV0070910_1717810205_f029326_v. Seqr search link - https://seqr.broadinstitute.org/variant_search/results/90addecf18f2a9e5eb54afcd50bcbd34?page=1&sort=in_omim

<img width="1289" alt="Screen Shot 2020-04-09 at 1 44 35 PM" src="https://user-images.githubusercontent.com/37872186/78924699-46215b00-7a68-11ea-8a19-a6464df93c07.png">

I get a 500 error when trying to do so. 

Case specific.

**Comment by hanars** [comment]
Note that while this is a bad bug that should be fixed, cross project search still has another open bug so fixing this will cause it to fail with 504 instead of 500: https://github.com/macarthur-lab/seqr-private/issues/790

(Note to self) There is an error generating aliases for search:
```
020-04-13 16:59:55,531 WARNING:  POST http://elasticsearch:9200/_aliases [status:403 request:0.006s]
2020-04-13 16:59:55,533 ERROR:  Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/seqr/seqr/views/apis/variant_search_api.py", line 74, in query_variants_handler
    variants, total_results = get_es_variants(results_model, sort=sort, page=page, num_results=per_page)
  File "/seqr/seqr/utils/elasticsearch/utils.py", line 89, in get_es_variants
    dataset_type=search.get('datasetType')
  File "/seqr/seqr/utils/elasticsearch/es_search.py", line 68, in __init__
    self._set_index_metadata()
  File "/seqr/seqr/utils/elasticsearch/es_search.py", line 96, in _set_index_metadata
    {'add': {'indices': self.samples_by_family_index.keys(), 'alias': alias}}
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/indices.py", line 490, in update_aliases
    "POST", "/_aliases", params=params, body=body
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 353, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 236, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 162, in _raise_error
    status_code, error_message, additional_info
AuthorizationException: AuthorizationException(403, u'cluster_block_exception', u'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];')
```

**Comment by hanars** [comment]
The seqr search link is working again and this page is now loading (I realize this is very delayed)
