### ISSUE TITLE
Local install issue

### ISSUE THREAD

**Issue by bnouyou** [broadinstitute/seqr#1343]
Hello,
I am doing the installation of Seqr with the actual version (using Docker).

At the step **Annotating and loading VCF callsets - option 2: annotate and load on-prem**, I don't understand what I should do with this command:
`gsutil -u your-gcloud-project-name cat gs://hail-us-vep/loftee-beta/GRCh37.tar  | tar xf  - & `

What is the `your-gcloud-project-name` ?

Thank you in advance for your help.

**Comment by bw2** [comment]
Hi @bnouyou , the data is stored in google buckets with  "requestor pays" enabled  (https://cloud.google.com/storage/docs/using-requester-pays). This way google doesn't charge us when people download this data.

**Comment by bw2** [comment]
The `your-gcloud-project-name` must be a google project with billing that you can use to download this data.

**Comment by bw2** [comment]
Just to double check, are you panning to run the loading pipeline using an on-prem spark cluster? or using something like google dataproc?

**Comment by bnouyou** [comment]
I am planning to use an on-prem spark cluster.

**Comment by bw2** [comment]
ok, the requestor-pays change is recent, and we need to document it better. 
gs://seqr-reference-data/ paths are now also requestor pays, and so we recommend downloading all data to your own filesystem. Let us know if this proves to be an issue.

**Comment by hanars** [comment]
So we shouldn't be using requestor pays now although we are trying to have everyone download the reference data once to their own filesystem, so maybe we need to update these docs

**Comment by bnouyou** [comment]
Hello,
So, how can I do to download these reference data files ?

**Comment by bw2** [comment]
Hi @bnouyou , apologies for the error on my part - we ended up deciding to disable requestor-pays on gs://seqr-reference-data. I've now updated the docs @ https://github.com/macarthur-lab/seqr/blob/master/deploy/LOCAL_INSTALL.md#annotating-and-loading-vcf-callsets---option-2-annotate-and-load-on-prem

**Comment by bnouyou** [comment]
Hello,

I have downloaded it, thank you.
I have run the command `python3 -m seqr_loading SeqrMTToESTask ... `
But I have an error:
`ValueError: vep_config_json_path path not found: /vep85-GRCh37-loftee-gcloud.json`

Is it because of this parameter:
`--vep-config-json-path /vep85-GRCh37-loftee-gcloud.json`

Should it be: `vep-GRCh37.json` in place of `vep85-GRCh37-loftee-gcloud.json` ?

**Comment by bnouyou** [comment]
So I have changed as I have written in my previous message, and it seems to be OK (I didn't have the message about the JSON file anymore).

But then I have this message, and I don't know what is it about:
`hail.utils.java.FatalError: SocketException: Connection reset`

**Comment by bw2** [comment]
Could you share the full error log?  Do you see the error immediately after the pipeline starts, or after it has been running for a while? 
If the error is related to the hail pipeline failing to connect to elasticsearch, can you describe whether you're running the pipeline and elasticsearch using the docker containers and docker-compose, or whether you're using some other custom installation?

**Comment by bnouyou** [comment]
The message appears imediatly after the pipeline starts (just aftfer the "hail").
See:
```
Welcome to
     __  __     <>__
    / /_/ /__  __/ /
   / __  / _ `/ / /
  /_/ /_/\_,_/_/_/   version 0.2.39-ef87446bd1c7
LOGGING: writing to /hail-20200624-1313-0.2.39-ef87446bd1c7.log
ERROR: [pid 152] Worker Worker(salt=237357676, workers=1, host=4240904c8757, username=root, pid=152) faile                              d    SeqrVCFToMTTask(source_paths=/input_vcfs/IOP_19-23298.combined.snp_indel.annovar.hg19_multianno.vcf.g                              z, dest_path=/output/, genome_version=37, vep_runner=VEP, reference_ht_path=/vep_data/seqr-reference-data/                              GRCh37/all_reference_data/combined_reference_data_grch37.ht, clinvar_ht_path=/vep_data/seqr-reference-data                              /GRCh37/clinvar/clinvar.GRCh37.2020-06-15.ht, hgmd_ht_path=None, sample_type=WES, dont_validate=False, dat                              aset_type=VARIANTS, remap_path=, subset_path=, vep_config_json_path=/vep-GRCh37.json)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "/hail-elasticsearch-pipelines/luigi_pipeline/seqr_loading.py", line 55, in run
    self.read_vcf_write_mt()
  File "/hail-elasticsearch-pipelines/luigi_pipeline/seqr_loading.py", line 64, in read_vcf_write_mt
    self.validate_mt(mt, self.genome_version, self.sample_type)
  File "/hail-elasticsearch-pipelines/luigi_pipeline/seqr_loading.py", line 107, in validate_mt
    sample_type_stats = HailMatrixTableTask.sample_type_stats(mt, genome_version)
  File "/hail-elasticsearch-pipelines/luigi_pipeline/lib/hail_tasks.py", line 99, in sample_type_stats
    ht = hl.read_table(ht_path)
  File "<decorator-gen-1296>", line 2, in read_table
  File "/usr/local/lib/python3.7/site-packages/hail/typecheck/check.py", line 585, in wrapper
    return __original_func(*args_, **kwargs_)
  File "/usr/local/lib/python3.7/site-packages/hail/methods/impex.py", line 2348, in read_table
    for rg_config in Env.backend().load_references_from_dataset(path):
  File "/usr/local/lib/python3.7/site-packages/hail/backend/spark_backend.py", line 324, in load_reference                              s_from_dataset
    return json.loads(Env.hail().variant.ReferenceGenome.fromHailDataset(self.fs._jfs, path))
  File "/usr/local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/local/lib/python3.7/site-packages/hail/backend/spark_backend.py", line 38, in deco
    'Error summary: %s' % (deepest, full, hail.__version__, deepest)) from None
hail.utils.java.FatalError: SocketException: Connection reset

Java stack trace:
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:990)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1400)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLC                              onnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:2                              64)
        at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.javanet.NetHttpRequest.execut                              e(NetHttpRequest.java:113)
        at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.javanet.NetHttpRequest.execut                              e(NetHttpRequest.java:84)
        at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.HttpRequest.execute(HttpReque                              st.java:1011)
        at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.auth.oauth2.TokenRequest.executeUn                              parsed(TokenRequest.java:322)
        at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.auth.oauth2.TokenRequest.execute(T                              okenRequest.java:346)
        at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.auth.oauth2.Credential.executeRefr                              eshToken(Credential.java:577)
        at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.auth.oauth2.GoogleCrede                              ntial.executeRefreshToken(GoogleCredential.java:372)
        at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.auth.oauth2.Credential.refreshToke                              n(Credential.java:494)
        at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.auth.oauth2.GoogleCrede                              ntial.fromStreamUser(GoogleCredential.java:860)
        at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.auth.oauth2.GoogleCrede                              ntial.fromStream(GoogleCredential.java:257)
        at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.CredentialFactory.getCreden                              tialFromJsonKeyFile(CredentialFactory.java:286)
        at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.CredentialConfiguration.get                              Credential(CredentialConfiguration.java:126)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.getCredential(GoogleHadoopFileSystemB                              ase.java:1613)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.createGcsFs(GoogleHadoopFileSystemBas                              e.java:1699)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.configure(GoogleHadoopFileSystemBase.                              java:1658)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase                              .java:683)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase                              .java:646)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at is.hail.io.fs.HadoopFS.fileStatus(HadoopFS.scala:148)
        at is.hail.io.fs.FS$class.isDir(FS.scala:106)
        at is.hail.io.fs.HadoopFS.isDir(HadoopFS.scala:57)
        at is.hail.expr.ir.RelationalSpec$.readMetadata(AbstractMatrixTableSpec.scala:31)
        at is.hail.expr.ir.RelationalSpec$.readReferences(AbstractMatrixTableSpec.scala:66)
        at is.hail.variant.ReferenceGenome$.fromHailDataset(ReferenceGenome.scala:587)
        at is.hail.variant.ReferenceGenome.fromHailDataset(ReferenceGenome.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)



Hail version: 0.2.39-ef87446bd1c7
Error summary: SocketException: Connection reset
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   SeqrVCFToMTTask__vep_data_seqr_r_VARIANTS__output__e60d981499   has s                              tatus   FAILED
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: There are 2 pending tasks possibly being run by other workers
DEBUG: There are 2 pending tasks unique to this worker
DEBUG: There are 2 pending tasks last scheduled by this worker
INFO: Worker Worker(salt=237357676, workers=1, host=4240904c8757, username=root, pid=152) was stopped. Shu                              tting down Keep-Alive thread
INFO:
===== Luigi Execution Summary =====

Scheduled 3 tasks of which:
* 1 complete ones were encountered:
    - 1 VcfFile(filename=/input_vcfs/IOP_19-23298.combined.snp_indel.annovar.hg19_multianno.vcf.gz)
* 1 failed:
    - 1 SeqrVCFToMTTask(...)
* 1 were left pending, among these:
    * 1 had failed dependencies:
        - 1 SeqrMTToESTask(...)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

```

I think this is because I run the pipeline on a VM which has not an internet access. Is it possible to run the pipeline without internet ?

**Comment by bw2** [comment]
Can you please try adding `--dont-validate`  to your command?
There's a default validation step at the beginning of the pipeline that check whether the user-provided arguments specifying whether the callset is GRCh37/38  and if it's exome vs. genome are correct in the sense that the callset contains the expected common variants based on the labels. If `--dont-validate` fixes the error, we can make that step work afterward.

**Comment by bnouyou** [comment]
Thank you !

I have added the `--dont-validate`and now it's OK I don't have this message.

The pipeline seems running, but I have an error at the begining:
`hail.utils.java.FatalError: HailException: Invalid locus 'chr1:1647871' found. Contig 'chr1' is not in the reference genome 'GRCh37'.`
I have download only the genome GRCh37, because my VCF files are done with the GRCh37.

**Comment by bw2** [comment]
By default the pipeline only accepts chromosome names that match the reference fasta. For GRCh37 this means no 'chr' prefix, and for GRCh38 it does have the 'chr' prefix. We might be able to add code to support both styes for GRCh37.

**Comment by bnouyou** [comment]
Do you know how I can change the chromosome notation ?
I have tried the `bcftools annotate --rename-chrs` command, but I still have some chromosomes written with the 'chr':
`Error summary: HailException: Invalid locus 'chr1_gl000192_random:133378' found. Contig 'chr1_gl000192_random' is not in the reference genome 'GRCh37'. `

Thank you for your help.

**Comment by bnouyou** [comment]
Hello,
I have tried many things, but each time I have the same error message about 'Invalid locus' which is not found in the reference genome GRCh37.
Is there a solution for making it work ?

I have used this VCF file with the previous version of Seqr, and I had no problem.

**Comment by bw2** [comment]
Hi @bnouyou ,
hail's list of GRCh37 contigs is:
```
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, X, Y, MT, GL000207.1, GL000226.1, GL000229.1, GL000231.1, GL000210.1, GL000239.1, GL000235.1, GL000201.1, GL000247.1, GL000245.1, GL000197.1, GL000203.1, GL000246.1, GL000249.1, GL000196.1, GL000248.1, GL000244.1, GL000238.1, GL000202.1, GL000234.1, GL000232.1, GL000206.1, GL000240.1, GL000236.1, GL000241.1, GL000243.1, GL000242.1, GL000230.1, GL000237.1, GL000233.1, GL000204.1, GL000198.1, GL000208.1, GL000191.1, GL000227.1, GL000228.1, GL000214.1, GL000221.1, GL000209.1, GL000218.1, GL000220.1, GL000213.1, GL000211.1, GL000199.1, GL000217.1, GL000216.1, GL000215.1, GL000205.1, GL000219.1, GL000224.1, GL000223.1, GL000195.1, GL000212.1, GL000222.1, GL000200.1, GL000193.1, GL000194.1, GL000225.1, GL000192.1
```
(for future reference, this is the output of  `python3 -c "import hail as hl; print(', '.join(hl.get_reference('GRCh37').contigs))"` )

Once the PR linked above is merged, the pipeline won't fail because of "chr" prefix, and will filter out VCF rows that aren't on the listed chromosomes.

**Comment by bnouyou** [comment]
Hello,
I will test when it will be merged. Thank you.
