### ISSUE TITLE
ProgrammingError at / in local install

### ISSUE THREAD

**Issue by jules-o** [broadinstitute/seqr#1603]
Hi,
Came back to local docker install after a break, containers start OK but then instead of seqr I get a ProgrammingError. I've removed all images and reinstalled from scratch but same thing. Ubuntu 20.04. Am I missing something obvious?

![Screenshot from 2021-01-13 00-21-12](https://user-images.githubusercontent.com/41348829/104386438-13dbe700-552d-11eb-9da8-0742ebcecffe.png)

Traceback:
Environment:

Request Method: GET
Request URL: http://localhost/

Django Version: 3.1.3
Python Version: 3.7.8
Installed Applications:
['seqr.apps.SuperuserAdminConfig',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.staticfiles',
 'guardian',
 'anymail',
 'seqr',
 'reference_data',
 'matchmaker',
 'social_django',
 'corsheaders',
 'hijack']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'seqr.utils.middleware.LogRequestMiddleware',
 'seqr.utils.middleware.JsonErrorMiddleware']

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 402, in __get__
    rel_obj = self.related.get_cached_value(instance)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]

During handling of the above exception ('userpolicy'), another exception occurred:
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

The above exception (relation "seqr_userpolicy" does not exist
LINE 1: ...cy_version", "seqr_userpolicy"."tos_version" FROM "seqr_user...
                                                             ^
) was the direct cause of the following exception:
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/seqr/seqr/views/react_app.py", line 26, in no_login_main_app
    initial_json['user'] = _get_json_for_initial_user(request.user)
  File "/seqr/seqr/views/react_app.py", line 36, in _get_json_for_initial_user
    if hasattr(user, 'userpolicy'):
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 241, in inner
    return func(self._wrapped, *args)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 410, in __get__
    rel_obj = self.get_queryset(instance=instance).get(**filter_args)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /
Exception Value: relation "seqr_userpolicy" does not exist
LINE 1: ...cy_version", "seqr_userpolicy"."tos_version" FROM "seqr_user...
                                                             ^

**Comment by hanars** [comment]
This apperas to be an issue with your database and code versions being out of sync. Try running
```
python manage.py makemigrations
python manage.py migrate
```

**Comment by jules-o** [comment]
Aha! That's fixed it - thank you!
