### ISSUE TITLE
 StructExpression instance has no field, method, or property 'AC'

### ISSUE THREAD

**Issue by veioenza** [broadinstitute/seqr#1671]
Then trying to ingest data to ES I am getting the following error on a local installation. 

python3 -m seqr_loading SeqrMTToESTask --local-scheduler \
    --reference-ht-path /seqr-reference-data/GRCh38/combined_reference_data_grch38.ht \
    --clinvar-ht-path /seqr-reference-data/GRCh38/clinvar.GRCh38.2020-06-15.ht \
    --vep-config-json-path /vep-GRCh38.json \
    --es-host elasticsearch \
    --es-index-min-num-shards 3 \
    --sample-type WES \
    --es-index ng1491g \
    --genome-version 38 \
    --source-paths /input_vcfs/NG149-1.g.vcf.gz \
    --dest-path /vep_data/NG149-1.g.mt
 
    [Stage 10:=====================================================>(499 + 1) / 500]ERROR: [pid 29] Worker Worker(salt=426937051, workers=1, host=8bef22f79545, username=root, pid=29) failed    SeqrVCFToMTTask(source_paths=/input_vcfs/NG149-1.g.vcf.gz, dest_path=/vep_data/NG149-1.g.mt, genome_version=38, vep_runner=VEP, reference_ht_path=/seqr-reference-data/GRCh38/combined_reference_data_grch38.ht, clinvar_ht_path=/seqr-reference-data/GRCh38/clinvar.GRCh38.2020-06-15.ht, hgmd_ht_path=None, sample_type=WES, dont_validate=False, dataset_type=VARIANTS, remap_path=, subset_path=, vep_config_json_path=/vep-GRCh38.json)
 
    Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "/hail-elasticsearch-pipelines/luigi_pipeline/seqr_loading.py", line 55, in run
    self.read_vcf_write_mt()
  File "/hail-elasticsearch-pipelines/luigi_pipeline/seqr_loading.py", line 79, in read_vcf_write_mt
    overwrite=True).select_annotated_mt()
  File "/hail-elasticsearch-pipelines/luigi_pipeline/lib/model/base_mt_schema.py", line 133, in annotate_all
    getattr(self, atn_fn[0])(overwrite=overwrite)
  File "/hail-elasticsearch-pipelines/luigi_pipeline/lib/model/base_mt_schema.py", line 64, in wrapper
    func_ret = func(self, *args, **kwargs)
  File "/hail-elasticsearch-pipelines/luigi_pipeline/lib/model/seqr_mt_schema.py", line 196, in ac
    return self.mt.info.AC[self.mt.a_index-1]
  File "/usr/local/lib/python3.7/site-packages/hail/expr/expressions/typed_expressions.py", line 1598, in __getattr__
    raise AttributeError(get_nice_attr_error(self, item))
AttributeError: StructExpression instance has no field, method, or property 'AC'
    Hint: use 'describe()' to show the names of all data fields.
DEBUG: 1 running tasks, waiting for next task to finish
 
Looks like it is complaining about the data fields. Is there a prefered method of created the input vcf files?

**Comment by hanars** [comment]
We assume all VCFs are joint called and we use the Broad's GATK for calling. @mike-w-wilson may be able to add more information about what field are expected/ required and how to get around any issues

**Comment by veioenza** [comment]
Resolved by making changes earlier in the pipeline

**Comment by cccnrc** [comment]
@veioenza what changes did you make?
