### ISSUE TITLE
SEQR docker-compose up -d error

### ISSUE THREAD

**Issue by cccnrc** [broadinstitute/seqr#1770]
I am getting into an error everytime I try to start seqr through docker-compose as recommended in [guidelines for local deployment](https://github.com/broadinstitute/seqr/blob/master/deploy/LOCAL_INSTALL.md) (working on an Ubuntu 20.04 machine with all specified requirements met). Even reinstalling everything with:
```
cd $SEQR_DIR
docker compose rm -s
docker compose up -d seqr
docker-compose logs -f seqr
```
shows me:
```
seqr_1             |   Downloading pyspark-2.4.1.tar.gz (215.7 MB)
seqr_1             |     ERROR: Command errored out with exit status 1:
seqr_1             |      command: /usr/local/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-frexg6r_/pyspark/setup.py'"'"'; __file__='"'"'/tmp/pip-install-frexg6r_/pyspark/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5md6f24w
seqr_1             |          cwd: /tmp/pip-install-frexg6r_/pyspark/
seqr_1             |     Complete output (47 lines):
seqr_1             |     Could not import pypandoc - required to package PySpark
seqr_1             |     WARNING: The wheel package is not available.
seqr_1             |       ERROR: Command errored out with exit status 1:
seqr_1             |        command: /usr/local/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-m0_zk3jp/pypandoc/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-m0_zk3jp/pypandoc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-cc3q5q6n
seqr_1             |            cwd: /tmp/pip-wheel-m0_zk3jp/pypandoc/
seqr_1             |       Complete output (8 lines):
seqr_1             |       no pandoc found, building platform unspecific wheel...
seqr_1             |       use 'python setup.py download_pandoc' to download pandoc.
seqr_1             |       usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
seqr_1             |          or: setup.py --help [cmd1 cmd2 ...]
seqr_1             |          or: setup.py --help-commands
seqr_1             |          or: setup.py cmd --help
seqr_1             |     
seqr_1             |       error: invalid command 'bdist_wheel'
seqr_1             |       ----------------------------------------
seqr_1             |       ERROR: Failed building wheel for pypandoc
seqr_1             |     ERROR: Failed to build one or more wheels
seqr_1             |     Traceback (most recent call last):
seqr_1             |       File "/usr/local/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
seqr_1             |         subprocess.check_call(cmd)
seqr_1             |       File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
seqr_1             |         raise CalledProcessError(retcode, cmd)
seqr_1             |     subprocess.CalledProcessError: Command '['/usr/local/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpueo2oxdi', '--quiet', 'pypandoc']' returned non-zero exit status 1.
seqr_1             |     
seqr_1             |     During handling of the above exception, another exception occurred:
seqr_1             |     
seqr_1             |     Traceback (most recent call last):
seqr_1             |       File "<string>", line 1, in <module>
seqr_1             |       File "/tmp/pip-install-frexg6r_/pyspark/setup.py", line 224, in <module>
seqr_1             |         'Programming Language :: Python :: Implementation :: PyPy']
seqr_1             |       File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
seqr_1             |         _install_setup_requires(attrs)
seqr_1             |       File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
seqr_1             |         dist.fetch_build_eggs(dist.setup_requires)
seqr_1             |       File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 698, in fetch_build_eggs
seqr_1             |         replace_conflicting=True,
seqr_1             |       File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
seqr_1             |         replace_conflicting=replace_conflicting
seqr_1             |       File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1066, in best_match
seqr_1             |         return self.obtain(req, installer)
seqr_1             |       File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1078, in obtain
seqr_1             |         return installer(requirement)
seqr_1             |       File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
seqr_1             |         return fetch_build_egg(self, req)
seqr_1             |       File "/usr/local/lib/python3.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
seqr_1             |         raise DistutilsError(str(e))
seqr_1             |     distutils.errors.DistutilsError: Command '['/usr/local/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpueo2oxdi', '--quiet', 'pypandoc']' returned non-zero exit status 1.
seqr_1             |     ----------------------------------------
seqr_1             | ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
seqr_1             | WARNING: You are using pip version 20.1.1; however, version 21.0.1 is available.
seqr_1             | You should consider upgrading via the '/usr/local/bin/python3.7 -m pip install --upgrade pip' command.
seqr_1             | + echo '*:*:*:*:docker-compose-postgres-password'
seqr_1             | + chmod 600 /root/.pgpass
seqr_1             | + cat /root/.pgpass
seqr_1             | *:*:*:*:docker-compose-postgres-password
seqr_1             | + psql --host postgres -U postgres -l
seqr_1             | + grep seqrdb
seqr_1             |  seqrdb            | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
seqr_1             | + /usr/local/bin/start_server.sh
seqr_1             | + '[' ']'
seqr_1             | + sleep 1000000000000
seqr_1             | [2021-03-30 18:10:06 +0000] [80] [INFO] Starting gunicorn 19.10.0
seqr_1             | [2021-03-30 18:10:06 +0000] [80] [INFO] Listening at: http://0.0.0.0:8000 (80)
seqr_1             | [2021-03-30 18:10:06 +0000] [80] [INFO] Using worker: sync
seqr_1             | [2021-03-30 18:10:06 +0000] [86] [INFO] Booting worker with pid: 86
seqr_1             | [2021-03-30 18:10:06 +0000] [87] [INFO] Booting worker with pid: 87
seqr_1             | [2021-03-30 18:10:06 +0000] [88] [INFO] Booting worker with pid: 88
seqr_1             | [2021-03-30 18:10:06 +0000] [86] [ERROR] Exception in worker process
seqr_1             | Traceback (most recent call last):
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 586, in spawn_worker
seqr_1             |     worker.init_process()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 135, in init_process
seqr_1             |     self.load_wsgi()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
seqr_1             |     self.wsgi = self.app.wsgi()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
seqr_1             |     self.callable = self.load()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
seqr_1             |     return self.load_wsgiapp()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
seqr_1             |     return util.import_app(self.app_uri)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
seqr_1             |     __import__(module)
seqr_1             |   File "/seqr/wsgi.py", line 24, in <module>
seqr_1             |     application = get_wsgi_application()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
seqr_1             |     django.setup(set_prefix=False)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
seqr_1             |     apps.populate(settings.INSTALLED_APPS)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 85, in populate
seqr_1             |     app_config = AppConfig.create(entry)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 94, in create
seqr_1             |     module = import_module(entry)
seqr_1             |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
seqr_1             |     return _bootstrap._gcd_import(name[level:], package, level)
seqr_1             | ModuleNotFoundError: No module named 'social_django'
seqr_1             | [2021-03-30 18:10:06 +0000] [86] [INFO] Worker exiting (pid: 86)
seqr_1             | [2021-03-30 18:10:06 +0000] [89] [INFO] Booting worker with pid: 89
seqr_1             | [2021-03-30 18:10:06 +0000] [87] [ERROR] Exception in worker process
seqr_1             | Traceback (most recent call last):
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 586, in spawn_worker
seqr_1             |     worker.init_process()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 135, in init_process
seqr_1             |     self.load_wsgi()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
seqr_1             |     self.wsgi = self.app.wsgi()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
seqr_1             |     self.callable = self.load()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
seqr_1             |     return self.load_wsgiapp()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
seqr_1             |     return util.import_app(self.app_uri)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
seqr_1             |     __import__(module)
seqr_1             |   File "/seqr/wsgi.py", line 24, in <module>
seqr_1             |     application = get_wsgi_application()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
seqr_1             |     django.setup(set_prefix=False)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
seqr_1             |     apps.populate(settings.INSTALLED_APPS)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 85, in populate
seqr_1             |     app_config = AppConfig.create(entry)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 94, in create
seqr_1             |     module = import_module(entry)
seqr_1             |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
seqr_1             |     return _bootstrap._gcd_import(name[level:], package, level)
seqr_1             | ModuleNotFoundError: No module named 'social_django'
seqr_1             | [2021-03-30 18:10:06 +0000] [87] [INFO] Worker exiting (pid: 87)
seqr_1             | Traceback (most recent call last):
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 210, in run
seqr_1             |     self.sleep()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 360, in sleep
seqr_1             |     ready = select.select([self.PIPE[0]], [], [], 1.0)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
seqr_1             |     self.reap_workers()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 528, in reap_workers
seqr_1             |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
seqr_1             | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
seqr_1             | 
seqr_1             | During handling of the above exception, another exception occurred:
seqr_1             | 
seqr_1             | Traceback (most recent call last):
seqr_1             |   File "/usr/local/bin/gunicorn", line 8, in <module>
seqr_1             |     sys.exit(run())
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
seqr_1             |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 223, in run
seqr_1             |     super(Application, self).run()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
seqr_1             |     Arbiter(self).run()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 232, in run
seqr_1             |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 345, in halt
seqr_1             |     self.stop()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 396, in stop
seqr_1             |     time.sleep(0.1)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
seqr_1             |     self.reap_workers()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 528, in reap_workers
seqr_1             |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
seqr_1             | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
seqr_1             | [2021-03-30 18:10:06 +0000] [88] [ERROR] Exception in worker process
seqr_1             | Traceback (most recent call last):
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 586, in spawn_worker
seqr_1             |     worker.init_process()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 135, in init_process
seqr_1             |     self.load_wsgi()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
seqr_1             |     self.wsgi = self.app.wsgi()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
seqr_1             |     self.callable = self.load()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
seqr_1             |     return self.load_wsgiapp()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
seqr_1             |     return util.import_app(self.app_uri)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
seqr_1             |     __import__(module)
seqr_1             |   File "/seqr/wsgi.py", line 24, in <module>
seqr_1             |     application = get_wsgi_application()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
seqr_1             |     django.setup(set_prefix=False)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
seqr_1             |     apps.populate(settings.INSTALLED_APPS)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 85, in populate
seqr_1             |     app_config = AppConfig.create(entry)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 94, in create
seqr_1             |     module = import_module(entry)
seqr_1             |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
seqr_1             |     return _bootstrap._gcd_import(name[level:], package, level)
seqr_1             | ModuleNotFoundError: No module named 'social_django'
seqr_1             | [2021-03-30 18:10:06 +0000] [88] [INFO] Worker exiting (pid: 88)
seqr_1             | [2021-03-30 18:10:06 +0000] [89] [ERROR] Exception in worker process
seqr_1             | Traceback (most recent call last):
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 586, in spawn_worker
seqr_1             |     worker.init_process()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 135, in init_process
seqr_1             |     self.load_wsgi()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
seqr_1             |     self.wsgi = self.app.wsgi()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
seqr_1             |     self.callable = self.load()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
seqr_1             |     return self.load_wsgiapp()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
seqr_1             |     return util.import_app(self.app_uri)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
seqr_1             |     __import__(module)
seqr_1             |   File "/seqr/wsgi.py", line 24, in <module>
seqr_1             |     application = get_wsgi_application()
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
seqr_1             |     django.setup(set_prefix=False)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
seqr_1             |     apps.populate(settings.INSTALLED_APPS)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 85, in populate
seqr_1             |     app_config = AppConfig.create(entry)
seqr_1             |   File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 94, in create
seqr_1             |     module = import_module(entry)
seqr_1             |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
seqr_1             |     return _bootstrap._gcd_import(name[level:], package, level)
seqr_1             | ModuleNotFoundError: No module named 'social_django'
seqr_1             | [2021-03-30 18:10:06 +0000] [89] [INFO] Worker exiting (pid: 89)

```
and the `localhost` is actually unreachable.

Any idea?

**Comment by hanars** [comment]
Maybe try changing the tag for the seqr image in your docker compose from `gcloud-prod` to the explicit tag for the latest image which is `20210322_170111`. We updated the docker image last week which might be the cause of that issue

**Comment by cccnrc** [comment]
Now it looks to load properly but if I try to create a user:
```
docker-compose exec seqr python manage.py createsuperuser
```
I got this error:
```
/usr/local/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.4) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/local/lib/python3.7/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
System check identified some issues:

WARNINGS:
social_django.Partial.data: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
	HINT: Use django.db.models.JSONField instead.
social_django.UserSocialAuth.extra_data: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
	HINT: Use django.db.models.JSONField instead.
```


Looking at logs:
```
/usr/local/lib/python3.7/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
```
longer logs:
```
seqr_1             | /usr/local/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.4) or chardet (3.0.4) doesn't match a supported version!
seqr_1             |   RequestsDependencyWarning)
seqr_1             | /usr/local/lib/python3.7/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
seqr_1             |   warnings.warn(msg)
seqr_1             | /usr/local/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.4) or chardet (3.0.4) doesn't match a supported version!
```

**Comment by hanars** [comment]
so the good news is thats not a seqr deployment issue, so your image/ installation are probably working. 

that error occurs because when you created the index  `ddd210383 ` the VCF you used had samples with IDs `DDDP130111`, `DDDP130112`, and `DDDP130113` but the seqr project you are trying to add the index to does not have individuals with those IDs so seqr is not sure who those samples correspond to. If you don't care about those samples, you can click the "ignore extra samples in callset" checkbox on that form and seqr will just ignore them. If you do want to include those samples you should exit the form and create or update individuals in your project with those IDs and then try to add the index after you do that.

**Comment by cccnrc** [comment]
ok @hanars thanks so much, I managed to understand how to update individuals info and now it looks like it took it. At this moment I see this "_**analysis in progress**_" status:
![Screenshot from 2021-04-01 10-04-08](https://user-images.githubusercontent.com/48554373/113263188-bfe1d280-92d1-11eb-9e59-303ecd643dfe.png)
but I see no working logs in neither `seqr` or `elasticsearch`. What is it exactly doing and how do I check it and know when finished?

**Comment by hanars** [comment]
you have to use the application to generate logs, this is a web-based analysis tool not a pipeline. There is no automation involved once you have it set up. Generally, people go to the trouble of setting up seqr because they are interested in doing variant analysis, which you do using the "search" functionality.

The "analysis in progress" status will be set until you manually update it. There is no automated way for seqr to know how you are progressing with your analysis, whether or not you have found a candidate variant etc. I would recommend that as you do your analysis, you update these statuses to help you track your work but there is no requirement that you do so

**Comment by cccnrc** [comment]
ok thank you again, got it, so what's the way to get the prioritized variants etc. out?

**Comment by hanars** [comment]
seqr does not prioritize variants for you. On the search page, you can set the criteria you are interested in and hit "search" and it will return all the variants that meet that search criteria. There are a few built-in searches you can choose that will set some criteria that we recommend as a good place to start. There are about a dozen options for how you would like to have these results sorted, but there is no single "priority" sort.

**Comment by bnouyou** [comment]
Hello,

I allow to ask, I have the exact same error described in the first post. Could you explain me how you have solved it ?
Thank you in advance.
