### ISSUE TITLE
Hail is not working for missing JAVA_HOME setting and failing accessing the gs files

### ISSUE THREAD

**Issue by ShifaSZ** [broadinstitute/seqr#2888]
**Describe the bug**
With current seqr docker image, Hail is not working for missing JAVA_HOME setting and failing in opening gs files.

The seqr uses Hail to check if the cram paths exist with the cron tool. The logs about the errors are as below.
```
checking bam/cram paths
 0%| | 0/38463 [00:00<?, ? samples/s]Initializing Hail with default parameters...
JAVA_HOME is not set
0%| | 0/38463 [00:00<?, ? samples/s]
Traceback (most recent call last): File "/seqr/manage.py", line 10, in <module> execute_from_command_line(sys.argv) File "/opt/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line utility.execute() File "/opt/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute self.fetch_command(subcommand).run_from_argv(self.argv) File "/opt/venv/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv self.execute(*args, **cmd_options) File "/opt/venv/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute output = self.handle(*args, **options) File "/seqr/seqr/management/commands/check_bam_cram_paths.py", line 40, in handle if not hl.hadoop_is_file(sample.file_path): File "/opt/venv/lib/python3.7/site-packages/hail/utils/hadoop_utils.py", line 160, in hadoop_is_file return Env.fs().is_file(path) File "/opt/venv/lib/python3.7/site-packages/hail/utils/java.py", line 100, in fs return Env.backend().fs File "/opt/venv/lib/python3.7/site-packages/hail/utils/java.py", line 76, in backend return Env.hc()._backend File "/opt/venv/lib/python3.7/site-packages/hail/utils/java.py", line 54, in hc init() File "<decorator-gen-1686>", line 2, in init File "/opt/venv/lib/python3.7/site-packages/hail/typecheck/check.py", line 577, in wrapper
 return __original_func(*args_, **kwargs_)
 File "/opt/venv/lib/python3.7/site-packages/hail/context.py", line 328, in init
 skip_logging_configuration=skip_logging_configuration
 File "<decorator-gen-1688>", line 2, in init_spark
 File "/opt/venv/lib/python3.7/site-packages/hail/typecheck/check.py", line 577, in wrapper
 return __original_func(*args_, **kwargs_)
 File "/opt/venv/lib/python3.7/site-packages/hail/context.py", line 388, in init_spark
 skip_logging_configuration, optimizer_iterations)
 File "/opt/venv/lib/python3.7/site-packages/hail/backend/spark_backend.py", line 152, in __init__
 pyspark.SparkContext._ensure_initialized(conf=conf)
 File "/opt/venv/lib/python3.7/site-packages/pyspark/context.py", line 331, in _ensure_initialized
 SparkContext._gateway = gateway or launch_gateway(conf)
 File "/opt/venv/lib/python3.7/site-packages/pyspark/java_gateway.py", line 108, in launch_gateway
 raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number
```

Besides that, even after installing JRE/JDK to the container, the Hail still can't open files from a path start with "gs://". The error messages are as below.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/seqr/validate_vcf.py", line 45, in import_vcf
    force_bgz=True, min_partitions=500)
  File "<decorator-gen-1356>", line 2, in import_vcf
  File "/opt/venv/lib/python3.7/site-packages/hail/typecheck/check.py", line 577, in wrapper
    return __original_func(*args_, **kwargs_)
  File "/opt/venv/lib/python3.7/site-packages/hail/methods/impex.py", line 2729, in import_vcf
    return MatrixTable(ir.MatrixRead(reader, drop_cols=drop_samples))
  File "/opt/venv/lib/python3.7/site-packages/hail/matrixtable.py", line 558, in __init__
    self._type = self._mir.typ
  File "/opt/venv/lib/python3.7/site-packages/hail/ir/base_ir.py", line 361, in typ
    self._compute_type()
  File "/opt/venv/lib/python3.7/site-packages/hail/ir/matrix_ir.py", line 70, in _compute_type
    self._type = Env.backend().matrix_type(self)
  File "/opt/venv/lib/python3.7/site-packages/hail/backend/spark_backend.py", line 291, in matrix_type
    jir = self._to_java_matrix_ir(mir)
  File "/opt/venv/lib/python3.7/site-packages/hail/backend/spark_backend.py", line 277, in _to_java_matrix_ir
    return self._to_java_ir(ir, self._parse_matrix_ir)
  File "/opt/venv/lib/python3.7/site-packages/hail/backend/spark_backend.py", line 267, in _to_java_ir
    ir._jir = parse(r(ir), ir_map=r.jirs)
  File "/opt/venv/lib/python3.7/site-packages/hail/backend/spark_backend.py", line 245, in _parse_matrix_ir
    return self._jbackend.parse_matrix_ir(code, ref_map, ir_map)
  File "/opt/venv/lib/python3.7/site-packages/py4j/java_gateway.py", line 1305, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/opt/venv/lib/python3.7/site-packages/hail/backend/py4j_backend.py", line 31, in deco
    raise fatal_error_from_java_error_triplet(deepest, full, error_id) from None
hail.utils.java.FatalError: UnsupportedFileSystemException: No FileSystem for scheme "gs"

Java stack trace:
org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "gs"
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3281)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3301)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361)
	at is.hail.io.fs.HadoopFS.getFileSystem(HadoopFS.scala:100)
	at is.hail.io.fs.HadoopFS.glob(HadoopFS.scala:154)
	at is.hail.io.fs.HadoopFS.$anonfun$globAll$1(HadoopFS.scala:136)
	at is.hail.io.fs.HadoopFS.$anonfun$globAll$1$adapted(HadoopFS.scala:135)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:315)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:313)
	at scala.collection.AbstractIterator.to(Iterator.scala:1429)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:307)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:307)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1429)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:294)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:288)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1429)
	at is.hail.io.fs.HadoopFS.globAll(HadoopFS.scala:141)
	at is.hail.io.vcf.MatrixVCFReader$.apply(LoadVCF.scala:1570)
	at is.hail.io.vcf.MatrixVCFReader$.fromJValue(LoadVCF.scala:1666)
	at is.hail.expr.ir.MatrixReader$.fromJson(MatrixIR.scala:89)
	at is.hail.expr.ir.IRParser$.matrix_ir_1(Parser.scala:1720)
	at is.hail.expr.ir.IRParser$.$anonfun$matrix_ir$1(Parser.scala:1646)
	at is.hail.utils.StackSafe$More.advance(StackSafe.scala:64)
	at is.hail.utils.StackSafe$.run(StackSafe.scala:16)
	at is.hail.utils.StackSafe$StackFrame.run(StackSafe.scala:32)
	at is.hail.expr.ir.IRParser$.$anonfun$parse_matrix_ir$1(Parser.scala:1986)
	at is.hail.expr.ir.IRParser$.parse(Parser.scala:1973)
	at is.hail.expr.ir.IRParser$.parse_matrix_ir(Parser.scala:1986)
	at is.hail.backend.spark.SparkBackend.$anonfun$parse_matrix_ir$2(SparkBackend.scala:691)
	at is.hail.backend.ExecuteContext$.$anonfun$scoped$3(ExecuteContext.scala:69)
	at is.hail.utils.package$.using(package.scala:640)
	at is.hail.backend.ExecuteContext$.$anonfun$scoped$2(ExecuteContext.scala:69)
	at is.hail.utils.package$.using(package.scala:640)
	at is.hail.annotations.RegionPool$.scoped(RegionPool.scala:17)
	at is.hail.backend.ExecuteContext$.scoped(ExecuteContext.scala:58)
	at is.hail.backend.spark.SparkBackend.withExecuteContext(SparkBackend.scala:310)
	at is.hail.backend.spark.SparkBackend.$anonfun$parse_matrix_ir$1(SparkBackend.scala:690)
	at is.hail.utils.ExecutionTimer$.time(ExecutionTimer.scala:52)
	at is.hail.utils.ExecutionTimer$.logTime(ExecutionTimer.scala:59)
	at is.hail.backend.spark.SparkBackend.parse_matrix_ir(SparkBackend.scala:689)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:750)



Hail version: 0.2.95-513139587f57
Error summary: UnsupportedFileSystemException: No FileSystem for scheme "gs"
```

**Link to page(s) where bug is occurring**

**Scope of the bug**
Broad instance of seqr or any other instances running with the same dockerized image.

**Screenshots**

**Comment by mike-w-wilson** [comment]
For the gs schema issue, I think the gcs connector needs to be installed `curl -sSL https://broad.io/install-gcs-connector | `python3``

**Comment by hanars** [comment]
With the new hail backend, we will be doing all hail-specific queries in the backend directly. Therefore, it does not make sense to fix the hail installation in seqr, it makes more sense to take this out and revert it to the slower-but-totally-functional way of checking paths directly

**Comment by hanars** [comment]
hail dependency has been removed and this should work now
