### ISSUE TITLE
Search error: Object of type AttrList is not JSON serializable

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#3033]
All searches in new AnVIL project error with "Object of type AttrList is not JSON serializable" https://seqr.broadinstitute.org/project/R0654_humanproject/family_page/F041818_wbstriob

Error report: https://console.cloud.google.com/errors/detail/CN_Xq8zMrK6oUQ;time=P30D?project=seqr-project&utm_source=error-reporting-notification&utm_medium=email&utm_content=new-error

Stack trace:
```
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/seqr/seqr/views/apis/variant_search_api.py", line 68, in query_variants_handler
    return create_json_response(response)
  File "/seqr/seqr/views/utils/json_utils.py", line 33, in create_json_response
    obj, json_dumps_params=dumps_params, encoder=DjangoJSONEncoderWithSets, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/django/http/response.py", line 605, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/seqr/seqr/views/utils/json_utils.py", line 13, in default
    return super(DjangoJSONEncoderWithSets, self).default(o)
  File "/opt/venv/lib/python3.7/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AttrList is not JSON serializable

```

**Comment by hanars** [comment]
There are 2 malformed AVIL indices that were loaded during a brief time period where we were using a now-unsupported schema for importing gnomad noncoding scores. The solution is to have @mike-w-wilson reload the indices 
```
r0654_humanproject__wgs__grch38__variants__v02__vcfv20221004__20221006
r0655_seqr__wes__grch38__variants__v02__vcfv20221007__20221007
```

**Comment by hanars** [comment]
deleted `r0654_humanproject__wgs__grch38__variants__v02__vcfv20221004__20221006` so this is now resolved
