### ISSUE TITLE
A logging error while loading RNAseq data

### ISSUE THREAD

**Issue by ShifaSZ** [broadinstitute/seqr#3268]
**Describe the bug**
When loading RNA-seq data, there are some logging errors (see the followings) on the console of my local environment.
```
--- Logging error ---
Traceback (most recent call last):
  File "/Users/shifa/opt/anaconda2/envs/mito/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/Users/shifa/opt/anaconda2/envs/mito/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/Users/shifa/opt/anaconda2/envs/mito/lib/python3.7/logging/__init__.py", line 611, in format
    s = self.formatMessage(record)
  File "/Users/shifa/dev/seqr/seqr/utils/logging_utils.py", line 40, in formatMessage
    return json.dumps(log_json)
  File "/Users/shifa/opt/anaconda2/envs/mito/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Users/shifa/opt/anaconda2/envs/mito/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/shifa/opt/anaconda2/envs/mito/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/shifa/opt/anaconda2/envs/mito/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
Call stack:
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 770, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
  File "/Users/shifa/opt/anaconda2/envs/mito/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  ...
    return view_func(request, *args, **kwargs)
  [Previous line repeated 1 more time]
  File "/Users/shifa/dev/seqr/seqr/views/apis/data_manager_api.py", line 390, in load_rna_seq_sample_data
    model_cls.bulk_create(request.user, [model_cls(sample=sample, **data) for data in data_by_gene.values()])
  File "/Users/shifa/dev/seqr/seqr/models.py", line 1052, in bulk_create
    cls.log_model_no_guid_bulk_update(models, user, 'create')
  File "/Users/shifa/dev/seqr/seqr/models.py", line 1044, in log_model_no_guid_bulk_update
    logger.info(f'{update_type} {db_entity}s', user, db_update=db_update)
  File "/Users/shifa/dev/seqr/seqr/utils/logging_utils.py", line 56, in info
    self._log(logging.INFO, *args, **kwargs)
  File "/Users/shifa/dev/seqr/seqr/utils/logging_utils.py", line 50, in _log
    self._logger.log(level, message, extra=dict(user=user, **kwargs))
Message: 'create RnaSeqOutliers'
Arguments: ()

```

The logging fails for `logger.info(f'{update_type} {db_entity}s', user, db_update=db_update)` because the `db_update` has a set field that can't be dumped to a string while formatting with `json.dumps(log_json)`.

An example value of `db_update` is `{'dbEntity': 'RnaSeqOutlier', 'numEntities': 1, 'parentEntityIds': {'S1730134926_RGP_123_3'}, 'updateType': 'bulk_delete'}` when the error happens. The cause of the error is that the `parentEntityIds` data is a set.

The error can be fixed easily by converting the set field to a list. But we should do more because these errors have never been caught by tests since the logger is always mocked in the tests.

The example RNAseq data I was loading has the following data.
```
sampleID	geneID	detail	pValue	padjust	zScore
RGP_123_3	ENSG00000240361		0.04	0.112	1.9
```
**Link to page(s) where bug is occurring**

**Scope of the bug**

**Screenshots**

**Comment by hanars** [comment]
fixed
