### ISSUE TITLE
Local install error: "database "reference_data_db" does not exist"

### ISSUE THREAD

**Issue by AunErki** [broadinstitute/seqr#4504]
Hello!

Once again I am doing seqr local install from the start.

This time I can't get the webpage up.
Request to webpage results with the following error in the docker log:
`seqr-1  | {"timestamp": "2024-11-28 12:04:35,109", "severity": "ERROR", "httpRequest": {"requestMethod": "GET", "requestUrl": "http://193.40.155.228/", "status": 500, "responseSize": 190557, "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0", "remoteIp": "185.50.98.142", "referer": null, "protocol": "HTTP/1.1"}, "message": "connection failed: database \"seqrdb\" does not exist", "traceback": "Traceback (most recent call last):\n  File \"/opt/venv/lib/python3.9/site-packages/django/db/backends/base/base.py\", line 289, in ensure_connection\n    self.connect()\n  File \"/opt/venv/lib/python3.9/site-packages/django/utils/asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n  File \"/opt/venv/lib/python3.9/site-packages/django/db/backends/base/base.py\", line 270, in connect\n    self.connection = self.get_new_connection(conn_params)\n  File \"/opt/venv/lib/python3.9/site-packages/django/utils/asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n  File \"/opt/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py\", line 275, in get_new_connection\n    connection = self.Database.connect(**conn_params)\n  File \"/opt/venv/lib/python3.9/site-packages/psycopg/connection.py\", line 119, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: database \"seqrdb\" does not exist\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/opt/venv/lib/python3.9/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/seqr/seqr/views/react_app.py\", line 42, in no_login_main_app\n    return render_app_html(request, **render_kwargs)\n  File \"/seqr/seqr/views/react_app.py\", line 63, in render_app_html\n    'warningMessages': [message.json() for message in WarningMessage.objects.all()],\n  File \"/opt/venv/lib/python3.9/site-packages/django/db/models/query.py\", line 398, in __iter__\n    self._fetch_all()\n  File \"/opt/venv/lib/python3.9/site-packages/django/db/models/query.py\", line 1881, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n  File \"/opt/venv/lib/python3.9/site-packages/django/db/models/query.py\", line 91, in __iter__\n    results = compiler.execute_sql(\n  File \"/opt/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py\", line 1560, in execute_sql\n    cursor = self.connection.cursor()\n  File \"/opt/venv/lib/python3.9/site-packages/django/utils/asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n  File \"/opt/venv/lib/python3.9/site-packages/django/db/backends/base/base.py\", line 330, in cursor\n    return self._cursor()\n  File \"/opt/venv/lib/python3.9/site-packages/django/db/backends/base/base.py\", line 306, in _cursor\n    self.ensure_connection()\n  File \"/opt/venv/lib/python3.9/site-packages/django/utils/asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n  File \"/opt/venv/lib/python3.9/site-packages/django/db/backends/base/base.py\", line 289, in ensure_connection\n    self.connect()\n  File \"/opt/venv/lib/python3.9/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/opt/venv/lib/python3.9/site-packages/django/db/backends/base/base.py\", line 289, in ensure_connection\n    self.connect()\n  File \"/opt/venv/lib/python3.9/site-packages/django/utils/asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n  File \"/opt/venv/lib/python3.9/site-packages/django/db/backends/base/base.py\", line 270, in connect\n    self.connection = self.get_new_connection(conn_params)\n  File \"/opt/venv/lib/python3.9/site-packages/django/utils/asyncio.py\", line 26, in inner\n    return func(*args, **kwargs)\n  File \"/opt/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py\", line 275, in get_new_connection\n    connection = self.Database.connect(**conn_params)\n  File \"/opt/venv/lib/python3.9/site-packages/psycopg/connection.py\", line 119, in connect\n    raise last_ex.with_traceback(None)\ndjango.db.utils.OperationalError: connection failed: database \"seqrdb\" does not exist\n", "@type": "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent"}`

Also, "docker compose exec seqr python manage.py update_all_reference_data --use-cached-omim  # Intialize reference data" command does not work and reports the following error:
`Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "/opt/venv/lib/python3.9/site-packages/psycopg/connection.py", line 119, in connect
    raise last_ex.with_traceback(None)
psycopg.OperationalError: connection failed: database "reference_data_db" does not exist`

`The above exception was the direct cause of the following exception:`

`Traceback (most recent call last):
  File "/seqr/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/seqr/reference_data/management/commands/update_all_reference_data.py", line 57, in handle
    update_gencode(LATEST_GENCODE_RELEASE, reset=True)
  File "/seqr/reference_data/management/commands/update_gencode.py", line 42, in update_gencode
    logger.info("Dropping the {} existing TranscriptInfo entries".format(TranscriptInfo.objects.count()))
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor = self.connection.cursor()
  File "/opt/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 330, in cursor
    return self._cursor()
  File "/opt/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 306, in _cursor
    self.ensure_connection()
  File "/opt/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "/opt/venv/lib/python3.9/site-packages/psycopg/connection.py", line 119, in connect
    raise last_ex.with_traceback(None)
django.db.utils.OperationalError: connection failed: database "reference_data_db" does not exist`

**Comment by hanars** [comment]
My apologies, it looks like we have a bug in our startup at the moment. In order to fix your installation, please run the following commands:
```
docker compose exec psql --host postgres -U postgres -c 'CREATE DATABASE reference_data_db';
docker compose exec psql --host postgres -U postgres -c 'CREATE DATABASE seqrdb';
docker compose exec seqr python manage.py migrate
docker compose exec seqr python manage.py migrate --database=reference_data
docker compose exec seqr python manage.py loaddata variant_searches
docker compose exec seqr python manage.py loaddata variant_tag_types
docker compose exec seqr python manage.py update_all_reference_data --use-cached-omim

```

This is an issue with first time set up and goign forward once you have run these you should have no trouble with using seqr. Again, I apologize for the issue

**Comment by AunErki** [comment]
Hi Hana!

Thank you for your help and clarifying the issue that I had.
I got it working by referencing to some older version of seqr in the docker compose file.
I believe that it did the same as the commands in your post.
I installed older version once and after that the latest version install also worked.

**Comment by hanars** [comment]
I am glad that worked. Because it was just a bug in the initial set up, once you have a deployment that is working I anticipate that all future updates will also not cause any issues and your deployment should be stable going forward. I apologize again for the inconvenience this bug caused!

**Comment by hanars** [comment]
The latest seqr release should fix this issue for anyone else creating a new installation going forward
